### ISSUE TITLE
ActionController::ParameterMissing: param is missing or the value is empty: task

### ISSUE THREAD

**Issue by saragilford** [saragilford/todo-with-sentry#1]
https://sentry.io/sara/todo-list/issues/405755008/

```
ActionController::ParameterMissing: param is missing or the value is empty: task
  app/controllers/tasks_controller.rb:73:in `task_params'
    params.fetch(:task).permit(:description, :completed)
  app/controllers/tasks_controller.rb:28:in `create'
    @task = Task.new(task_params)
...
(70 additional frame(s) were not displayed)

ActionController::ParameterMissing: param is missing or the value is empty: task
```

**Comment by saragilford** [comment]
Hey, I think this might be related to this: https://github.com/saragilford/todo-with-sentry/issues/2

**Comment by saragilford** [comment]
Hey, I think this issue might be related to this: https://github.com/saragilford/todo-with-sentry/issues/2
